blueprint:
  name: "Garage: Auto-Close on Departure"
  description: >-
    Automatically close the garage door when a car leaves or when nobody is home.
    Optionally sends a mobile notification to one or more devices with the reason.
    Respects a "keep open" helper toggle so you can override the auto-close when needed.

    Designed as a companion to the Garage Card
    (https://github.com/KadenThomp36/garage-card). The card visualizes your
    garage door and car presence — this blueprint handles the auto-close logic.
    Point both at the same door and car presence entities, and use the same
    keep_open input_boolean the card toggles to prevent auto-close from the dashboard.
  domain: automation
  author: KadenThomp36
  source_url: https://github.com/KadenThomp36/garage-card/blob/main/blueprints/auto_close_on_departure.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    garage_door:
      name: Garage Door
      description: The garage door cover entity to control.
      selector:
        entity:
          filter:
            - domain: cover
    car_presence_sensors:
      name: Car Presence Sensors
      description: >-
        One or more binary sensors that track car presence in the garage.
        The door will close when any of these turn off (car departs).
      selector:
        entity:
          filter:
            - domain: binary_sensor
          multiple: true
    departure_delay:
      name: Departure Delay
      description: How long to wait after a car is detected as gone before closing the door.
      default: 5
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
    close_when_nobody_home:
      name: Close When Nobody Home
      description: Also close the door when the home zone reaches 0 occupants.
      default: true
      selector:
        boolean: {}
    keep_open_helper:
      name: Keep Open Helper (optional)
      description: >-
        An input_boolean that prevents auto-close when turned on.
        Leave empty to disable this check.
      default: ""
      selector:
        entity:
          filter:
            - domain: input_boolean
    notify_devices:
      name: Notification Devices (optional)
      description: >-
        Mobile devices to notify when the door auto-closes. Select multiple
        devices if needed. Leave empty to disable notifications.
      default: []
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true
    notification_title:
      name: Notification Title
      description: Title shown in the notification.
      default: "Garage Auto-Closed"
      selector:
        text: {}
    include_timestamp:
      name: Include Timestamp
      description: Append the current time to the notification message.
      default: true
      selector:
        boolean: {}

triggers:
  - trigger: state
    entity_id: !input car_presence_sensors
    to: "off"
    for:
      seconds: !input departure_delay
    id: car_departed
  - trigger: state
    entity_id: zone.home
    to: "0"
    id: nobody_home

conditions:
  - condition: state
    entity_id: !input garage_door
    state: open

actions:
  - variables:
      keep_open: !input keep_open_helper
      close_nobody_home: !input close_when_nobody_home
  - condition: template
    value_template: >-
      {{ keep_open == none or keep_open == '' or states(keep_open) == 'off' }}
  - choose:
      - conditions:
          - condition: trigger
            id: nobody_home
          - condition: template
            value_template: "{{ close_nobody_home }}"
        sequence:
          - action: cover.close_cover
            target:
              entity_id: !input garage_door
          - variables:
              reason: "Garage door closed — nobody home"
      - conditions:
          - condition: trigger
            id: car_departed
        sequence:
          - action: cover.close_cover
            target:
              entity_id: !input garage_door
          - variables:
              reason: "Garage door closed — car departed"
  - variables:
      devices: !input notify_devices
      title: !input notification_title
      show_time: !input include_timestamp
      message: >-
        {{ reason }}{% if show_time %} at {{ now().strftime('%I:%M %p') }}{% endif %}
  - repeat:
      for_each: "{{ devices }}"
      sequence:
        - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ title }}"
            message: "{{ message }}"

mode: single
