blueprint:
  name: "Garage: Auto-Open on Arrival"
  description: >-
    Automatically open the garage door when a person arrives near home while
    driving. Uses a zone trigger (e.g., a "Neighborhood" zone) and the phone's
    activity sensor to confirm the person is in a vehicle — preventing the door
    from opening when walking or biking nearby. Includes a configurable timeout —
    if the door doesn't open in time, a warning notification is sent.

    Designed as a companion to the Garage Card
    (https://github.com/KadenThomp36/garage-card). The card visualizes your
    garage in real time — this blueprint handles opening the door automatically
    so it's already open by the time you pull into the driveway.
  domain: automation
  author: KadenThomp36
  source_url: https://github.com/KadenThomp36/garage-card/blob/main/blueprints/auto_open_on_arrival.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    garage_door:
      name: Garage Door
      description: The garage door cover entity to open.
      selector:
        entity:
          filter:
            - domain: cover
    person_entity:
      name: Person
      description: The person entity to track.
      selector:
        entity:
          filter:
            - domain: person
    arrival_zone:
      name: Arrival Zone
      description: >-
        The zone that triggers the door to open when the person enters it.
        Create a zone around your neighborhood (e.g., 500m radius) so the door
        opens before you reach the driveway.
      selector:
        entity:
          filter:
            - domain: zone
    activity_sensor:
      name: Activity Sensor (optional)
      description: >-
        The phone's activity sensor (e.g., sensor.my_iphone_activity) to confirm
        the person is driving. Must report "Automotive" when in a vehicle.
        Leave empty to open the door on any arrival regardless of activity.
      default: ""
      selector:
        entity:
          filter:
            - domain: sensor
    open_timeout:
      name: Open Timeout
      description: >-
        How long to wait for the door to finish opening before giving up.
        If the door doesn't reach "open" in this time, a warning is sent.
      default: 2
      selector:
        number:
          min: 1
          max: 10
          unit_of_measurement: minutes
    notify_devices:
      name: Notification Devices (optional)
      description: >-
        Mobile devices to notify when the door auto-opens or fails to open.
        Select multiple devices if needed. Leave empty to disable notifications.
      default: []
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true
    notification_title:
      name: Notification Title
      description: Title shown in the notification.
      default: "Garage Auto-Opened"
      selector:
        text: {}
    include_timestamp:
      name: Include Timestamp
      description: Append the current time to the notification message.
      default: true
      selector:
        boolean: {}

triggers:
  - trigger: zone
    entity_id: !input person_entity
    zone: !input arrival_zone
    event: enter

conditions: []

actions:
  - variables:
      activity: !input activity_sensor
  - condition: template
    value_template: >-
      {{ activity == none or activity == '' or states(activity) == 'Automotive' }}
  - action: cover.open_cover
    target:
      entity_id: !input garage_door
  - wait_for_trigger:
      - trigger: state
        entity_id: !input garage_door
        to: open
    timeout:
      minutes: !input open_timeout
    continue_on_timeout: true
  - variables:
      devices: !input notify_devices
      title: !input notification_title
      show_time: !input include_timestamp
      door_opened: "{{ wait.trigger is not none }}"
      reason: "Garage door opened — arrival detected"
      message: >-
        {% if door_opened %}{{ reason }}{% if show_time %} at {{ now().strftime('%I:%M %p') }}{% endif %}{% else %}WARNING: Garage door failed to open — check manually{% endif %}
  - repeat:
      for_each: "{{ devices }}"
      sequence:
        - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ title if door_opened else 'Garage Door Warning' }}"
            message: "{{ message }}"

mode: single
