blueprint:
  name: "Garage: Auto-Close if Left Open"
  description: >-
    Close the garage door if it's been left open — either after a period of no
    occupancy or at a specific time (e.g., midnight safety close). Sends a mobile
    notification to one or more devices. Respects a "keep open" helper toggle.

    Designed as a companion to the Garage Card
    (https://github.com/KadenThomp36/garage-card). The card shows your garage
    door state in real time — this blueprint ensures it doesn't stay open
    indefinitely. Use the same keep_open input_boolean the card toggles to
    override auto-close directly from your dashboard.
  domain: automation
  author: KadenThomp36
  source_url: https://github.com/KadenThomp36/garage-card/blob/main/blueprints/auto_close_left_open.yaml
  homeassistant:
    min_version: "2024.6.0"
  input:
    garage_door:
      name: Garage Door
      description: The garage door cover entity to control.
      selector:
        entity:
          filter:
            - domain: cover
    occupancy_sensor:
      name: Occupancy Sensor (optional)
      description: >-
        A binary sensor for garage occupancy (e.g., person detection from a camera).
        The door closes after the inactivity timeout when this turns off.
        Leave empty to disable inactivity-based closing.
      default: ""
      selector:
        entity:
          filter:
            - domain: binary_sensor
    inactivity_minutes:
      name: Inactivity Timeout
      description: >-
        Minutes of no occupancy before the door auto-closes.
        Only used if an occupancy sensor is configured.
      default: 15
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes
    safety_close_time:
      name: Safety Close Time (optional)
      description: >-
        Time of day to force-close the door regardless of occupancy (e.g., midnight).
        Leave empty to disable.
      default: ""
      selector:
        time: {}
    keep_open_helper:
      name: Keep Open Helper (optional)
      description: >-
        An input_boolean that prevents auto-close when turned on.
        Leave empty to disable this check.
      default: ""
      selector:
        entity:
          filter:
            - domain: input_boolean
    notify_devices:
      name: Notification Devices (optional)
      description: >-
        Mobile devices to notify when the door auto-closes. Select multiple
        devices if needed. Leave empty to disable notifications.
      default: []
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: true
    notification_title:
      name: Notification Title
      description: Title shown in the notification.
      default: "Garage Auto-Closed"
      selector:
        text: {}
    include_timestamp:
      name: Include Timestamp
      description: Append the current time to the notification message.
      default: true
      selector:
        boolean: {}

triggers:
  - trigger: state
    entity_id: !input occupancy_sensor
    to: "off"
    for:
      minutes: !input inactivity_minutes
    id: inactivity
  - trigger: time
    at: !input safety_close_time
    id: safety_close

conditions:
  - condition: state
    entity_id: !input garage_door
    state: open

actions:
  - variables:
      keep_open: !input keep_open_helper
  - choose:
      - conditions:
          - condition: trigger
            id: inactivity
          - condition: template
            value_template: >-
              {{ keep_open == none or keep_open == '' or states(keep_open) == 'off' }}
        sequence:
          - action: cover.close_cover
            target:
              entity_id: !input garage_door
          - variables:
              reason: "Garage door closed — no activity detected"
      - conditions:
          - condition: trigger
            id: safety_close
        sequence:
          - action: cover.close_cover
            target:
              entity_id: !input garage_door
          - variables:
              reason: "Garage door closed — scheduled safety close"
  - variables:
      devices: !input notify_devices
      title: !input notification_title
      show_time: !input include_timestamp
      message: >-
        {{ reason }}{% if show_time %} at {{ now().strftime('%I:%M %p') }}{% endif %}
  - repeat:
      for_each: "{{ devices }}"
      sequence:
        - action: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
          data:
            title: "{{ title }}"
            message: "{{ message }}"

mode: restart
